version: '2.3'

services:
  zeppelin:
    image: apache/zeppelin:0.8.1
    volumes:
      - ./zeppelin/logs:/logs
      - ./zeppelin/notebook:/notebook
      - ./zeppelin/zeppelin-site.xml.template:/zeppelin/conf/zeppelin-site.xml
      - ./zeppelin/interpreter.json:/zeppelin/conf/interpreter.json
      - ./JobsAndGrowth/data:/data
    environment:
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_LOG_DIR=/logs
    ports:
      - 7077:7077
      - 8080:8080
    privileged: true
    command: /zeppelin/bin/zeppelin.sh

  site:
    image: jekyll/jekyll:latest
    volumes:
      - ./site/:/srv/jekyll
    ports:
      - 4000:4000
    command: jekyll serve --future
