version: '2.3'

services:
  nginx:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt_nginx/data/certbot/conf:/etc/letsencrypt

  certbot:
    volumes:
      - ./letsencrypt_nginx/data/certbot/conf:/etc/letsencrypt
      - ./letsencrypt_nginx/data/certbot/www:/var/www/certbot

  site:
    command: jekyll serve --config _config.yml,_config.prod.yml --future
